spring.data.mongodb.uri=mongodb+srv://andresbena_db_user:UZcS7r5cH5Vdazd@cards.lged8xv.mongodb.net/flashcardsdb?appName=Cards
spring.data.mongodb.auto-index-creation=true

spring.mail.host=localhost
spring.mail.port=2525

